# Generated by Django 5.1.5 on 2025-03-12 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('telefono', models.CharField(max_length=10)),
                ('correo', models.EmailField(max_length=60)),
                ('contrasenia', models.CharField(max_length=45)),
                ('rol', models.CharField(choices=[('empleado', 'empleado'), ('cliente', 'cliente')], max_length=10)),
                ('codigo_verificacion', models.IntegerField()),
            ],
        ),
    ]
