# Generated by Django 5.1.5 on 2025-03-18 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='codigo_verificacion',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
