# Generated by Django 5.1.5 on 2025-03-19 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_usuario_codigo_verificacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('empleado', 'empleado'), ('cliente', 'cliente')], default='cliente', max_length=10),
        ),
    ]
