# Generated by Django 5.1.5 on 2025-03-19 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_alter_usuario_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('empleado', 'empleado'), ('cliente', 'cliente'), ('admin', 'admin')], default='cliente', max_length=10),
        ),
    ]
