# Generated by Django 5.1.5 on 2025-03-23 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_logs'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='logs',
            table='logs',
        ),
    ]
