# Generated by Django 5.1.5 on 2025-03-20 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_alter_usuario_rol'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={'permissions': [('admin', 'Control total'), ('empleado', 'funcionalidades basicas'), ('cliente', 'acceso a la plataforma de compra')]},
        ),
    ]
