# Generated by Django 5.1.5 on 2025-04-02 18:14

import datetime
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('proovedores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Insumo',
            fields=[
                ('id_insumo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
                ('tipo', models.CharField(max_length=45)),
                ('tipo_medida', models.CharField(max_length=45)),
                ('cantidad', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('precio_unitario', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('estatus', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'insumo',
            },
        ),
        migrations.CreateModel(
            name='Compra_insumo',
            fields=[
                ('id_compra_insumo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
                ('cantidad', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('cantidad_restante', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('caducidad', models.DateField(validators=[django.core.validators.MinValueValidator(datetime.date(2025, 4, 2))])),
                ('total', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('precio_unitario', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('estatus', models.CharField(default='', max_length=15)),
                ('id_proovedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compra_insumo_proovedor', to='proovedores.proovedor')),
                ('id_insumo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compra_insumo_insumo', to='inventario_insumos.insumo')),
            ],
            options={
                'db_table': 'compra_insumo',
            },
        ),
        migrations.CreateModel(
            name='Merma_insumo',
            fields=[
                ('id_merma_insumo', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('motivo', models.CharField(max_length=45)),
                ('fecha', models.DateField(null=True)),
                ('id_compra_insumo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='merma_compra_insumo', to='inventario_insumos.compra_insumo')),
            ],
            options={
                'db_table': 'merma_insumo',
            },
        ),
    ]
