# Generated by Django 5.1.5 on 2025-03-18 03:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('proovedores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Insumo',
            fields=[
                ('id_insumo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
                ('tipo', models.CharField(max_length=45)),
                ('tipo_medida', models.CharField(max_length=45)),
                ('cantidad', models.IntegerField()),
                ('estatus', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Compra_insumo',
            fields=[
                ('id_compra_insumo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
                ('cantidad', models.FloatField()),
                ('cantidad_restante', models.FloatField()),
                ('caducidad', models.DateField()),
                ('precio', models.FloatField()),
                ('id_proovedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compra_insumo_proovedor', to='proovedores.proovedor')),
                ('id_insumo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compra_insumo_insumo', to='inventario_insumos.insumo')),
            ],
            options={
                'db_table': 'compra_insumo',
            },
        ),
        migrations.CreateModel(
            name='Merma_insumo',
            fields=[
                ('id_merma_insumo', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.FloatField()),
                ('motivo', models.CharField(max_length=45)),
                ('id_compra_insumo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='merma_compra_insumo', to='inventario_insumos.compra_insumo')),
            ],
            options={
                'db_table': 'merma_insumo',
            },
        ),
    ]
