# Generated by Django 5.1.5 on 2025-03-24 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario_insumos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insumo',
            name='precio_unitario',
            field=models.FloatField(default=0),
        ),
    ]
