<<<<<<< HEAD
# Generated by Django 5.1.5 on 2025-04-04 18:49
=======
# Generated by Django 5.1.5 on 2025-04-03 05:08
>>>>>>> branch_ruben

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventario_insumos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='merma_insumo',
            name='id_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='merma_insumo_usuario', to=settings.AUTH_USER_MODEL),
        ),
    ]
