# Generated by Django 5.1.5 on 2025-03-18 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario_insumos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='insumo',
            table='insumo',
        ),
    ]
