<<<<<<< HEAD
# Generated by Django 5.1.5 on 2025-03-26 08:24
=======
# Generated by Django 5.1.5 on 2025-03-25 19:49
>>>>>>> 41544858cbbcb5a5c4e98f3b02f1186925d54593

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventario_insumos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='merma_insumo',
            name='id_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='merma_insumo_usuario', to=settings.AUTH_USER_MODEL),
        ),
    ]
