# Generated by Django 5.1.5 on 2025-04-08 03:22

import datetime
import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario_insumos', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra_insumo',
            name='fecha_registro',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='compra_insumo',
            name='caducidad',
            field=models.DateField(validators=[django.core.validators.MinValueValidator(datetime.date(2025, 4, 8))]),
        ),
    ]
