# Generated by Django 5.1.5 on 2025-04-07 00:32

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario_insumos', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra_insumo',
            name='caducidad',
            field=models.DateField(validators=[django.core.validators.MinValueValidator(datetime.date(2025, 4, 7))]),
        ),
    ]
