# Generated by Django 5.1.5 on 2025-03-29 05:01

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario_insumos', '0004_alter_compra_insumo_caducidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra_insumo',
            name='caducidad',
            field=models.DateField(validators=[django.core.validators.MinValueValidator(datetime.date(2025, 3, 29))]),
        ),
    ]
