# Generated by Django 5.1.7 on 2025-03-20 01:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('galletas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Merma_producto',
            fields=[
                ('id_merma', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('motivo', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'merma_producto',
            },
        ),
        migrations.CreateModel(
            name='Lote_galleta',
            fields=[
                ('id_lote_galleta', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_preparacion', models.DateField()),
                ('estatus', models.CharField(max_length=10)),
                ('cantidad_galletas', models.IntegerField()),
                ('id_galleta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lote_galleta_galleta', to='galletas.galleta')),
            ],
            options={
                'db_table': 'lote_galleta',
            },
        ),
    ]
