# Generated by Django 5.1.5 on 2025-04-01 10:23

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('galletas', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lote_galleta',
            fields=[
                ('id_lote_galleta', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_preparacion', models.DateField()),
                ('estatus', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Mezclando', 'Mezclando'), ('Formando', 'Formando'), ('Horneando', 'Horneando'), ('Enfriando', 'Enfriando'), ('Completado', 'Completado'), ('Caducado', 'Caducado')], default='Pendiente', max_length=45)),
                ('cantidad_galletas', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('caducidad_lote', models.DateField(blank=True, null=True)),
                ('id_galleta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lote_galleta_galleta', to='galletas.galleta')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lote_galleta_usuario', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'lote_galleta',
                'ordering': ['-id_lote_galleta'],
            },
        ),
        migrations.CreateModel(
            name='Merma_producto',
            fields=[
                ('id_merma', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('motivo', models.CharField(max_length=45)),
                ('id_lote_galleta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='merma_lote_galleta', to='produccion.lote_galleta')),
            ],
            options={
                'db_table': 'merma_producto',
            },
        ),
    ]
