<<<<<<< HEAD
# Generated by Django 5.1.5 on 2025-04-04 19:10

import django.core.validators
=======
# Generated by Django 5.1.5 on 2025-04-02 19:00

>>>>>>> 303a5e4 (idk)
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('galletas', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Merma_producto',
            fields=[
                ('id_merma', models.AutoField(primary_key=True, serialize=False)),
<<<<<<< HEAD
                ('cantidad', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
=======
                ('cantidad', models.IntegerField()),
>>>>>>> 303a5e4 (idk)
                ('motivo', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'merma_producto',
            },
        ),
        migrations.CreateModel(
            name='Lote_galleta',
            fields=[
                ('id_lote_galleta', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_preparacion', models.DateField()),
<<<<<<< HEAD
                ('estatus', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Mezclando', 'Mezclando'), ('Formando', 'Formando'), ('Horneando', 'Horneando'), ('Enfriando', 'Enfriando'), ('Completado', 'Completado'), ('Caducado', 'Caducado')], default='Pendiente', max_length=45)),
                ('cantidad_galletas', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('caducidad_lote', models.DateField(blank=True, null=True)),
=======
                ('estatus', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Mezclando', 'Mezclando'), ('Formando', 'Formando'), ('Horneando', 'Horneando'), ('Enfriando', 'Enfriando'), ('Completado', 'Completado')], default='Pendiente', max_length=15)),
                ('cantidad_galletas', models.IntegerField()),
>>>>>>> 303a5e4 (idk)
                ('id_galleta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lote_galleta_galleta', to='galletas.galleta')),
            ],
            options={
                'db_table': 'lote_galleta',
<<<<<<< HEAD
                'ordering': ['-id_lote_galleta'],
=======
>>>>>>> 303a5e4 (idk)
            },
        ),
    ]
