# Generated by Django 5.1.5 on 2025-03-28 00:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('produccion', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lote_galleta',
            name='id_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lote_galleta_usuario', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='merma_producto',
            name='id_lote_galleta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='merma_lote_galleta', to='produccion.lote_galleta'),
        ),
    ]
