# Generated by Django 5.1.5 on 2025-03-29 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lote_galleta',
            options={'ordering': ['-fecha_preparacion']},
        ),
    ]
