# Generated by Django 5.1.5 on 2025-03-29 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0003_alter_lote_galleta_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lote_galleta',
            options={'ordering': ['-id_lote_galleta']},
        ),
    ]
