<<<<<<< HEAD
# Generated by Django 5.1.5 on 2025-04-04 18:49

import django.core.validators
=======
# Generated by Django 5.1.5 on 2025-04-03 05:08

import django.core.validators
import django.db.models.deletion
>>>>>>> branch_ruben
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
<<<<<<< HEAD
=======
        ('inventario_insumos', '0002_initial'),
>>>>>>> branch_ruben
    ]

    operations = [
        migrations.CreateModel(
<<<<<<< HEAD
            name='Detalle_receta',
            fields=[
                ('id_detalle_receta', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
            ],
            options={
                'db_table': 'detalle_receta',
            },
        ),
        migrations.CreateModel(
=======
>>>>>>> branch_ruben
            name='Galleta',
            fields=[
                ('id_galleta', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('descripcion', models.CharField(max_length=100)),
<<<<<<< HEAD
                ('costo', models.FloatField(validators=[django.core.validators.MinValueValidator(1)])),
                ('precio_venta', models.FloatField(validators=[django.core.validators.MinValueValidator(1)])),
                ('cantidad', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('cantidad_receta', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('peso_unidad', models.FloatField(validators=[django.core.validators.MinValueValidator(1)])),
                ('duracion_promedio', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
=======
                ('costo', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('precio_venta', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('cantidad', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('cantidad_receta', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('peso_unidad', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('duracion_promedio', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
>>>>>>> branch_ruben
            ],
            options={
                'db_table': 'galleta',
            },
        ),
<<<<<<< HEAD
=======
        migrations.CreateModel(
            name='Detalle_receta',
            fields=[
                ('id_detalle_receta', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('id_insumo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalle_receta_insumo', to='inventario_insumos.insumo')),
                ('id_galleta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalle_receta_galleta', to='galletas.galleta')),
            ],
            options={
                'db_table': 'detalle_receta',
            },
        ),
>>>>>>> branch_ruben
    ]
