<<<<<<< HEAD
# Generated by Django 5.1.5 on 2025-03-20 04:59
=======
# Generated by Django 5.1.7 on 2025-03-20 01:54
>>>>>>> 70b9c6cccbc93c3d9f82c57460f6382878f780c3

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventario_insumos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Galleta',
            fields=[
                ('id_galleta', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('descripcion', models.CharField(max_length=100)),
                ('precio_venta', models.FloatField()),
                ('cantidad', models.IntegerField()),
                ('peso_unidad', models.FloatField()),
                ('duracion_promedio', models.IntegerField()),
            ],
            options={
                'db_table': 'galleta',
            },
        ),
        migrations.CreateModel(
            name='Detalle_receta',
            fields=[
                ('id_detalle_receta', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.FloatField()),
                ('id_insumo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalle_receta_insumo', to='inventario_insumos.insumo')),
                ('id_galleta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalle_receta_galleta', to='galletas.galleta')),
            ],
            options={
                'db_table': 'detalle_receta',
            },
        ),
    ]
