# Generated by Django 5.1.5 on 2025-03-28 00:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Detalle_receta',
            fields=[
                ('id_detalle_receta', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
            ],
            options={
                'db_table': 'detalle_receta',
            },
        ),
        migrations.CreateModel(
            name='Galleta',
            fields=[
                ('id_galleta', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('descripcion', models.CharField(max_length=100)),
                ('precio_venta', models.FloatField()),
                ('cantidad', models.IntegerField(default=0)),
                ('cantidad_receta', models.IntegerField()),
                ('peso_unidad', models.FloatField()),
                ('duracion_promedio', models.IntegerField()),
            ],
            options={
                'db_table': 'galleta',
            },
        ),
    ]
