# Generated by Django 5.1.5 on 2025-04-04 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galletas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleta',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='galleta/'),
        ),
    ]
