# Generated by Django 5.1.5 on 2025-04-02 18:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('galletas', '0001_initial'),
        ('inventario_insumos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalle_receta',
            name='id_insumo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalle_receta_insumo', to='inventario_insumos.insumo'),
        ),
        migrations.AddField(
            model_name='detalle_receta',
            name='id_galleta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalle_receta_galleta', to='galletas.galleta'),
        ),
    ]
