# Generated by Django 5.1.5 on 2025-03-28 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galletas', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleta',
            name='cantidad_receta',
            field=models.IntegerField(default=30),
            preserve_default=False,
        ),
    ]
