# Generated by Django 5.1.5 on 2025-03-27 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galletas', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleta',
            name='cantidad',
            field=models.IntegerField(default=0),
        ),
    ]
