# Generated by Django 5.1.5 on 2025-03-27 05:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galletas', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleta',
            name='cantidad_por_lote',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='detalle_receta',
            name='cantidad',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='galleta',
            name='cantidad',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='galleta',
            name='duracion_promedio',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='galleta',
            name='peso_unidad',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='galleta',
            name='precio_venta',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
