# Generated by Django 5.1.5 on 2025-03-28 03:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galletas', '0003_galleta_cantidad_receta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='galleta',
            name='cantidad_por_lote',
        ),
        migrations.AlterField(
            model_name='galleta',
            name='cantidad_receta',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
