# Generated by Django 5.1.5 on 2025-03-28 01:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galletas', '0003_galleta_cantidad_por_lote_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleta',
            name='costo',
            field=models.FloatField(default=30, validators=[django.core.validators.MinValueValidator(0)]),
            preserve_default=False,
        ),
    ]
