# Generated by Django 5.1.5 on 2025-04-04 18:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('galletas', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id_venta', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_venta', models.DateField()),
                ('tipo', models.CharField(max_length=30)),
                ('estatus', models.CharField(max_length=30)),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='venta_cliente', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'venta',
            },
        ),
        migrations.CreateModel(
            name='Detalle_venta',
            fields=[
                ('id_detalle_venta', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.FloatField()),
                ('precio_galleta', models.FloatField()),
                ('presentacion', models.CharField(default='unidad', max_length=15)),
                ('id_galleta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalle_venta_galleta', to='galletas.galleta')),
                ('id_venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalle_venta_venta', to='ventas.venta')),
            ],
            options={
                'db_table': 'detalle_venta',
            },
        ),
    ]
