# Generated by Django 5.1.5 on 2025-03-28 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalle_venta',
            name='tipo_unidad',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='total',
        ),
        migrations.AddField(
            model_name='detalle_venta',
            name='presentacion',
            field=models.CharField(default='unidad', max_length=15),
        ),
    ]
