# Generated by Django 5.1.5 on 2025-03-22 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venta',
            name='total',
        ),
        migrations.AddField(
            model_name='detalle_venta',
            name='precio_galleta',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
    ]
