# Generated by Django 5.1.5 on 2025-03-22 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0002_remove_venta_total_detalle_venta_precio_galleta'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalle_venta',
            name='presentacion',
            field=models.CharField(default='unidad', max_length=15),
        ),
    ]
