# Generated by Django 5.1.5 on 2025-04-06 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proovedor',
            fields=[
                ('id_proovedor', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('nombre_contacto', models.CharField(max_length=30)),
                ('telefono', models.CharField(max_length=12)),
                ('correo', models.EmailField(max_length=45)),
                ('direccion', models.CharField(max_length=100)),
                ('ciudad', models.CharField(max_length=15)),
                ('estado', models.CharField(max_length=15)),
                ('codigo_postal', models.CharField(max_length=7)),
                ('estatus', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo'), ('bloqueado', 'Bloqueado')], max_length=10)),
            ],
            options={
                'db_table': 'proovedor',
            },
        ),
    ]
