# Generated by Django 5.1.7 on 2025-03-20 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proovedores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proovedor',
            name='estatus',
            field=models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo'), ('bloqueado', 'Bloqueado')], default='activo', max_length=10),
        ),
    ]
